### ISSUE TITLE
Non-spatial data integration

### ISSUE THREAD

**Issue by mossnicholas** [aertslab/ScoMAP#2]
Hi,

I would like to integrate into virtual cells scATAC and RNA-seq datasets from the same cell type, but have no spatial information, and generate a set of correlations from those cells. I don't see this from the vignette - is it possible to initialize a virtual object without spatial information, only read counts?

Thank you!
Nicholas

**Comment by cbravo93** [comment]
Hi @mossnicholas !

If none of the cell types in the data set map to spatial cluster, ScoMAP can be run without providing a template. An empty virtual frame can be generated and all cells can be treated as external groups. This code is at the end of the section 1.4 in the tutorial, then you can continue as usual. I add the code here with some extra comments that may be useful :)

```
# Initialize empty VM
NonSpatial_VM <- setNames(data.frame(matrix(ncol = 11, nrow = 0)), c("x", "y", "R", "G", "B", "color", "cluster", "cluster_color", "cluster_refined", "cluster_refined_color", "cluster_annot"))
# Add external groups
# Any number works here for x and y, it will just create some random positions/cells in squared format. 
x <- 0 
y <- 0
# For number of cells I would recommend no more that you have in the layer where you have the less, otherwise it will bootstrap with many repeats later on. For color you can put anything, the coordinates and the color is just to keep the same format as when having spatially located cell types or both spatial and non-spatial. The code will work with non-spatial only too. And lastly, for the last parameter (the cluster name), try to match it with the names you have for the RNA and ATAC labels (preferebly the same between both too).
NonSpatial_VM <- addExternalCluster(NonSpatial_VM, x=x, y=y, number_cells=40, color=Spatial_ColVar['PM_lateral'], 'PM_lateral')
NonSpatial_VM <- addExternalCluster(NonSpatial_VM, x=x+20, y=y, number_cells=40, color=Spatial_ColVar['PM_medial'], 'PM_medial')
NonSpatial_VM <- addExternalCluster(NonSpatial_VM, x=x+40, y=y, number_cells=40, color=Spatial_ColVar['Glia'], 'Glia')
NonSpatial_VM <- addExternalCluster(NonSpatial_VM, x=x+60, y=y, number_cells=40, color=Spatial_ColVar['twi_cells'], 'twi_cells')
NonSpatial_VM <- addExternalCluster(NonSpatial_VM, x=x+80, y=y, number_cells=40, color=Spatial_ColVar['Hemocytes'], 'Hemocytes')
# Plot the annotated VM
Spatial_ColVar <- readRDS("Templates/Spatial_ColVar.Rds") # Color variable
plotAnnotatedVM(NonSpatial_VM, colVar=Spatial_ColVar, inset=c(-0.35,0))
```

Cheers!

C

**Comment by mossnicholas** [comment]
For a particular cell type, I have a RNA-seq count matrix and an ATAC-seq feature matrix (different cells, not from shared-profiling assay). Sorry, perhaps I'm missing it or misunderstanding the functionality of the package, but where do I input those  data matrices to allow for integration into the virtual cells. My ultimate goal is to determine enhancer-gene relationships, using the integrated RNA and ATAC-seq data from different datasets.

**Comment by cbravo93** [comment]
Yes, this is exactly what the package is intended for. You can follow the tutorial as it is, using the sections about Non-spatially located cell types. In the `Mapping single-cell RNA-seq data` section it explains how to load you scRNA-seq data, and in the `Mapping single-cell ATAC-seq data` it explains how to load your scATAC-seq data.

Cheers!

C
